### ISSUE TITLE
bin_count * nonempty_bins

### ISSUE THREAD

**Issue by shuaizzZ** [DHPO/GHM_Loss.pytorch#1]
这一步是什么意思呢，没有看到，希望您能有空解释一下。
gd = bin_count * nonempty_bins

**Comment by shuaizzZ** [comment]
不应该是gd = bin_count * self._bins吗？

**Comment by DHPO** [comment]
这个是论文作者的一个改进，可以看[这个issue](https://github.com/libuyu/GHM_Detection/issues/13#issue-420860127)

**Comment by shuaizzZ** [comment]
尝试把他用在语义分割上，效果非常差。。。。

**Comment by DHPO** [comment]
用`self._bins`和`nonempty_bins`结果会有很大差异吗？

我对语义分割不太熟悉，不好意思

**Comment by shuaizzZ** [comment]
差异不大，设了100个bin，基本上都是有效的。语义分割其实也是分类（对像素分类），可能我改的不对吧，不过速度上相对于交叉熵慢了近2倍，主要是里面那个循环很耗时，torch要是有统计tensor中每种元素的个数这种函数就好了哈哈哈。
